name: Pull Request

on:
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      name: Checkout
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0'
    - run: dotnet test
